// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1glFiIXPEjVFwKuc4tc30GMVt_xfhA5E',
    appId: '1:401094204328:web:ac3b0d67da4e0ca3661b9d',
    messagingSenderId: '401094204328',
    projectId: 'waterwise-2cba6',
    authDomain: 'waterwise-2cba6.firebaseapp.com',
    storageBucket: 'waterwise-2cba6.appspot.com',
    measurementId: 'G-H1LM8F75TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhAv3ovg2AulH91bIWg4YCpCxOnrTiNsA',
    appId: '1:401094204328:android:db8d2377d219a643661b9d',
    messagingSenderId: '401094204328',
    projectId: 'waterwise-2cba6',
    storageBucket: 'waterwise-2cba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYHpdxl4zSROBEoVowzyq1VEWqGa00xU',
    appId: '1:401094204328:ios:5bf9f52ed21d122c661b9d',
    messagingSenderId: '401094204328',
    projectId: 'waterwise-2cba6',
    storageBucket: 'waterwise-2cba6.appspot.com',
    iosBundleId: 'com.example.waterwize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoYHpdxl4zSROBEoVowzyq1VEWqGa00xU',
    appId: '1:401094204328:ios:5bf9f52ed21d122c661b9d',
    messagingSenderId: '401094204328',
    projectId: 'waterwise-2cba6',
    storageBucket: 'waterwise-2cba6.appspot.com',
    iosBundleId: 'com.example.waterwize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1glFiIXPEjVFwKuc4tc30GMVt_xfhA5E',
    appId: '1:401094204328:web:5cbcf2a566d8ab77661b9d',
    messagingSenderId: '401094204328',
    projectId: 'waterwise-2cba6',
    authDomain: 'waterwise-2cba6.firebaseapp.com',
    storageBucket: 'waterwise-2cba6.appspot.com',
    measurementId: 'G-6EQ8D4WC50',
  );
}
